#!/bin/bash
# Default values
DISPLAY_NUM=":0"
URLS=()
CHROME_BIN="chromium"
CHROME_COMMAND="$CHROME_BIN --incognito --disable-infobars --disable-suggestions-service --no-first-run --start-fullscreen --new-window"
#CHROME_COMMAND="chromium-browser --incognito --disable-infobars --disable-suggestions-service --no-first-run --start-fullscreen --new-window"

export DISPLAY="$DISPLAY_NUM"
                                 
# Function to parse command line arguments
parse_args() {
    while getopts "u:d:" opt; do
        case ${opt} in
            u)
                URLS+=("$OPTARG")
                ;;
            d)
                DISPLAY_NUM="$OPTARG"
                ;;
            \?)
                echo "Invalid option: -$OPTARG" >&2
                exit 1
                ;;
        esac
    done
}
 
# Function to kill all chromium-browser processes
kill_chrome() {
    pkill -f $CHROME_BIN
}
 
# Function to create a new workspace and launch chromium-browser with specified URL
launch_chrome() {
    local workspace=$1
    local url=$2

echo "Using DISPLAY $DISPLAY_NUM" &
echo "Opening ${URLS[$i]}" &
$CHROME_COMMAND ${URLS[$i]} &
}
 
# Main execution starts here
parse_args "$@"
               
# Kill all existing chromium-browser processes
kill_chrome

#export DISPLAY=$DISPLAY_NUM
i3-msg workspace "i3dash---> init..."

# Create workspaces and launch chromium-browser for each URL
for ((i=-1; i<${#URLS[@]}; i++)); do
    workspace=$((i+1))
    url="${URLS[$i]}"

#echo i3-msg workspace $((i+1))
i3-msg workspace "i3dash $((i+1))" & sleep 5 
launch_chrome
done

#   
# You can run this script in a terminal by providing the URLs as command-line arguments using the `-u` flag. For example:
#                                                                                                                       
#   i3dashctl -u "https://espn.com" -u "https://reddit.com" -u "https://digg.com"
#
#

