#!/bin/bash
# Default values
DISPLAY_NUM=""
URLS=()
CHROME_BIN="chromium"
CHROME_COMMAND="$CHROME_BIN --incognito --disable-infobars --disable-suggestions-service --no-first-run --start-fullscreen --new-window"
TOGGLE_INTERVAL=""

# Function to parse command line arguments
parse_args() {
    while getopts "u:d:t:" opt; do
        case ${opt} in
            u)
                URLS+=("$OPTARG")
                ;;
            d)
                DISPLAY_NUM="$OPTARG"
                ;;
	    t)
		TOGGLE_INTERVAL="$OPTARG"
		;;
#            b)
#		CHROME_BIN="$OPTARG"
#		;;
            \?)
                echo "Invalid option: -$OPTARG" >&2
                exit 1
                ;;
        esac
    done
}

# Function to kill all chromium-browser processes
kill_chrome() {
    pkill -f $CHROME_BIN
}
 
# Function to create a new workspace and launch chromium-browser with specified URL
launch_chrome() {
    local workspace=$1
    local url=$2
echo "         Using DISPLAY $DISPLAY_NUM" &
echo "         Opening ${URLS[$i]}" &
$CHROME_COMMAND ${URLS[$i]} &> /dev/null &
sleep 3
i3-msg [instance="^$CHROME_BIN$"] fullscreen disable &> /dev/null &
}

toggle_workspace() {
  i3-msg workspace next &> /dev/null
}


# Main execution starts here
parse_args "$@"
               
# Kill all existing chromium-browser processes
kill_chrome

export DISPLAY=:$DISPLAY_NUM
echo " "
echo "  Initializing..."
echo "   Toggle Interval: $TOGGLE_INTERVAL"
echo " "
# Create workspaces and launch chromium-browser for each URL
for ((i=0; i<${#URLS[@]}; i++)); do
    workspace=$((i+1))
    url="${URLS[$i]}"
echo "   i3Dash $((i+1))"
echo "       ${URLS[$i]}"
i3-msg workspace "  $((i+1))" &> /dev/null 
sleep 5
launch_chrome
echo " "

done

# Start toggling i3 workspaces
if [ "$TOGGLE_INTERVAL" ]; then
while true; do
  toggle_workspace
  sleep $TOGGLE_INTERVAL
 done
fi

#   
# You can run this script in a terminal by providing the URLs as command-line arguments using the `-u` flag. For example:
#                                                                                                                       
#   i3dashctl -u "https://espn.com" -u "https://reddit.com" -u "https://digg.com"
#
#

